const List<Map<String, dynamic>> medicines = [
  {
    'name': 'Advil',
    'genericName': 'Ibuprofen',
    'categories': [
      'Fever',
      'Headache',
      'Pain Reliever'],
    'image': 'assets/images/medicines/advil.png',
    'description': 'This medicine is indicated to reduce fever and to relieve mild to moderate pain and inflammation associated with dysmenorrhea, headache including migraine, postoperative pain, dental pain and musculoskeletal and joint disorders.',
    'dosage':'200 mg Ibuprofen ',
    'directions of use': '1-2 tablets every 4-6 hours, not to exceed a maximum daily dose of 1200 mg or 6 softgel capsules, unless directed by a doctor. The smallest effective dose should be used.',
    'administration': 'Should be taken with food: Take immediately after meal.',
    'contraindication': 'Contraindicated in: Known hypersensitivity to ibuprofen or NSAIDs; History of asthma, urticaria, or allergic reactions after taking aspirin or NSAIDs; Active or history of gastrointestinal bleeding/ulceration; Severe heart failure; Severe liver dysfunction; Severe kidney dysfunction; Last trimester of pregnancy; Patients with high blood pressure or heart disease should consult doctor before use.',
    'ageRestriction': '13',
    'interactions': [
      'aspirin',
      'warfarin',
      'heparin',
      'pradaxa',
      'xarelto',
      'eliquis',
      'alcohol',
      'furosemide',
      'hydrochlorothiazide',
      'spironolactone',
      'lithium',
      'methotrexate',
      'ibuprofen',
      'naproxen',
      'diclofenac',
      'celecoxib',
      'meloxicam'
    ],
    'activeIngredient': 'ibuprofen'
  },

  {
    'name': 'Alaxan FR',
    'genericName': 'Ibuprofen + Paracetamol',
    'categories': ['Pain Reliever', 'Fever', 'Headache'],
    'image': 'assets/images/medicines/alaxan_fr.png',
    'description': 'Relief of mild to moderately severe pain of musculoskeletal origin example, myalgia, arthritis, rheumatism, sprain, strain, bursitis, tendonitis, backache and stiff neck. Relief of tension headache, dysmenorrhea, toothache and pain after tooth extraction and minor surgical operations. Reduction of fever.',
    'dosage': '200 mg Ibuprofen + 325 mg Paracetamol',
    'directions of use': '1 capsule every 6 hours or as prescribed by the physician.',
    'administration': 'Should be taken with food: Take immediately after meals.',
    'contraindication': 'Do not use in: Known hypersensitivity to components; Active peptic ulcer; Severe heart, kidney or liver failure; Patients with asthma who are sensitive to aspirin or NSAIDs; High blood pressure (hypertension); History of GI bleeding; Third trimester of pregnancy; Children under 12 years.',
    'ageRestriction': '12',
    'interactions': [
      'aspirin',
      'ibuprofen',
      'naproxen',
      'diclofenac',
      'celecoxib',
      'meloxicam',
      'warfarin',
      'alcohol',
      'heparin',
      'pradaxa', 
      'methotrexate',
      'lisinopril',
      'enalapril',
      'ramipril',
      'captopril',
      'paracetamol',
      'acetaminophen'
    ],
    'activeIngredient': 'ibuprofen, paracetamol'
  },

  {
    'name': 'Ascof Forte',
    'genericName': 'Lagundi',
    'categories': ['Cough'],
    'image': 'assets/images/medicines/ascof_forte.png',
    'description': 'For the relief of cough due to common cold and flu, bronchitis, and other respiratory tract infections.',
    'dosage': '600 mg Lagundi',
    'directions of use': 'Adults and children 12 years and older: 1 capsule 3 times daily.',
    'administration': 'May be taken with or without food.',
    'contraindication': 'Hypersensitivity to Lagundi or any component of the product.',
    'ageRestriction': '12',
    'interactions': [
      'cetirizine',
      'loratadine',
      'diphenhydramine',
      'salbutamol',
      'ventolin',
      'albuterol',
      'theophylline'
    ],
    'activeIngredient': 'lagundi leaf extract'
  },

  {
    'name': 'Bioflu',
    'genericName': 'Phenylephrine + Chlorphenamine + Paracetamol',
    'categories': ['Cold', 'Flu', 'Fever'],
    'image': 'assets/images/medicines/bioflu.png',
    'description': 'This medicine is used for the relief of clogged nose, runny nose, cough from postnasal drip, itchy & watery eyes, sneezing, headache, sore throat, body aches, and fever associated with the common cold, allergic rhinitis, sinusitis, flu, and other minor respiratory tract infections. It also helps decongest sinus openings and passages and protect respiratory cells against common cold flu viruses.',
    'dosage': '10 mg Phenylephrine + 2 mg Chlorphenamine + 500 mg Paracetamol',
    'directions of use': '1 tablet every 6 hours as needed.',
    'administration': 'May be taken with or without food: May be given with food or milk if stomach upset occurs.',
    'contraindication': 'Do not use in: Severe hypertension and heart disease; Diabetes; Hyperthyroidism; Taking MAO inhibitors; Glaucoma; Kidney or liver disease; Asthma patients should consult doctor first; Pregnancy and breastfeeding.',
    'ageRestriction': '12',
    'interactions': [
      'epinephrine',
      'norepinephrine',
      'halothane',
      'isoflurane',
      'selegiline',
      'moclobemide',
      'phenelzine',
      'amitriptyline',
      'imipramine',
      'nortriptyline',
      'doxepin',
      'phenothiazines',
      'phentolamine',
      'propranolol',
      'atenolol',
      'metoprolol',
      'methyldopa',
      'alprazolam',
      'diazepam',
      'lorazepam',
      'zolpidem',
      'warfarin',
      'phenobarbital',
      'phenytoin',
      'metoclopramide',
      'domperidone',
      'cholestyramine',
      'paracetamol',
      'acetaminophen'
    ],
    'activeIngredient': 'phenylephrine, chlorphenamine, paracetamol'
  },

  {
    'name': 'Biogesic',
    'genericName': 'Paracetamol',
    'categories': [
      'Fever',
      'Headache',
      'Pain Reliever'
      'flu'
    ],
    'image': 'assets/images/medicines/biogesic.png',
    'description': 'Biogesic is indicated for the treatment of mild to moderate pain such as headache, backache, migraine, toothache, menstrual pain, muscular aches, and reduction of fever.',
    'dosage': '500 mg Paracetamol',
    'directions of use': '1-2 tablets every 4-6 hours as needed. Do not exceed 8 tablets in 24 hours.',
    'needsSpecificTiming': true,
    'administration': 'May be taken with or without food.',
    'contraindication': 'Contraindicated in: Hypersensitivity to paracetamol; Severe liver disease; Severe kidney disease; Patients with G6PD deficiency; Use with caution in patients with: Anemia, Lung disease, Heart disease, Kidney or liver dysfunction.',
    'ageRestriction': '12',
    'interactions': [
      'warfarin',
      'metoclopramide',
      'cholestyramine',
      'phenobarbital',
      'phenytoin',
      'alcohol',
      'ethanol',
      'acetaminophen',
      'paracetamol'
    ],
    'activeIngredient': 'paracetamol'
  },

  {
    'name': 'Buscopan Venus',
    'genericName': 'Hyoscine N-butylbromide + Paracetamol',
    'categories': ['Abdominal Pain', 'Menstrual Pain'], // Updated categories
    'image': 'assets/images/medicines/buscopan.png',
    'description': 'Hyoscine-N-butylbromide + Paracetamol (Buscopan Venus) is an antispasmodic analgesic combination used specifically for the relief from the pain of abdominal cramps including menstrual cramps and urinary tract spasm. Not recommended for general pain or fever.',
    'dosage': '10 mg Hyoscine N-butylbromide + 500 mg Paracetamol',
    'directions of use': '1-2 tablets 3 times daily. The total daily dose should not exceed 6 tablets. The tablets should not be chewed, but swallowed in whole with a sufficient amount of water. Hyoscine-N-butylbromide + Paracetamol (Buscopan Venus) should not be taken over prolonged period of time (for more than 3 days) without a prescription from the physician.',
    'administration': 'Take before meals.',
    'contraindication': 'Hyoscine-N-Butylbromide (Buscopan Venus) is contraindicated in known hypersensitivity to hyoscine butylbromide, or paracetamol or other components of the drug; myasthenia gravis; mechanical stenosis in the gastrointestinal tract; paralytical or obstructive ileus; megacolon; severe hepatocellular insufficiency(Child-Pugh C).',
    'ageRestriction': '10',
    'interactions': [
      'zolpidem',
      'eszopiclone',
      'phenobarbital',
      'phenytoin',
      'carbamazepine',
      'rifampicin',
      'alcohol',
      'warfarin',
      'zidovudine',
      'probenecid',
      'cholestyramine',
      'amitriptyline',
      'imipramine',
      'nortriptyline',
      'doxepin',
      'mirtazapine',
      'cetirizine',
      'loratadine',
      'diphenhydramine',
      'chlorpromazine',
      'haloperidol',
      'risperidone',
      'quinidine',
      'amantadine',
      'disopyramide',
      'tiotropium',
      'ipratropium',
      'atropine',
      'metoclopramide',
      'propranolol',
      'atenolol',
      'metoprolol',
      'paracetamol',
      'acetaminophen'
    ],
    'activeIngredient': 'hyoscine N-butylbromide, paracetamol'
  },

  {
    'name': 'Coldzep',
    'genericName': 'Phenylephrine + Chlorphenamine + Paracetamol',
    'categories': ['Cold', 'Flu', 'Fever'],
    'image': 'assets/images/medicines/coldzep.png',
    'description': 'For relief of symptoms associated with colds and flu including nasal congestion, runny nose, fever and body aches.',
    'dosage': '25 mg Phenylephrine + 2 mg Chlorphenamine + 500 mg Paracetamol',
    'directions of use': '1 tablet every 6 hours as needed.',
    'administration': 'May be taken with or without food.',
    'contraindication': 'Hypersensitivity to any component, severe hypertension.',
    'ageRestriction': '12',
    'interactions': ['MAOIs', 'alcohol', 'sedatives', 'paracetamol'],
    'activeIngredient': 'phenylephrine, chlorphenamine, paracetamol'
  },

  {
    'name': 'Diatabs',
    'genericName': 'Loperamide',
    'needsSpecificTiming': false,
    'categories': ['Antidiarrheal'],
    'image': 'assets/images/medicines/diatabs.png',
    'description': 'This medicine is used for the following conditions: Control and symptomatic relief of: acute non-specific diarrhea, chronic diarrhea associated with inflammatory bowel disease. In addition to using loperamide for diarrhea, it is important to replace that fluid and salt loss with the use of oral rehydration solution (ORS) and/or by drinking plenty of fluids.',
    'dosage': '2 mg Loperamide',
    'directions of use': 'Initial: 2 capsules, then 1 capsule after each loose bowel movement. Maximum: 8 capsules daily.',
    'administration': 'May be taken with or without food.',
    'contraindication': 'Acute dysentery, bacterial enterocolitis.',
    'ageRestriction': '12',
    'interactions': [
      'azithromycin',
      'amoxicillin',
      'ciprofloxacin',
      'doxycycline',
      'erythromycin',
      'kremil-s',
      'kremil-s advance',
      'maalox',
      'gaviscon',
      'tums'
    ],
    'activeIngredient': 'loperamide hydrochloride'
  },

  {
    'name': 'Flanax',
    'genericName': 'Naproxen Sodium', 
    'categories': ['Pain Reliever', 'Anti-inflammatory', 'Fever'],
    'image': 'assets/images/medicines/flanax.png',
    'description': 'For the relief of mild to moderate pain, fever, and inflammation. It is also indicated for the relief of pain associated with postpartum cramping and dysmenorrhea.',
    'dosage': '275 mg Naproxen Sodium',
    'directions of use': 'The recommended starting dose is 2 tablets, followed by 1 tablet every 8 hrs as required. The maximum recommended daily dose is 5 tablets (1375 mg).',
    'administration': 'Should be taken with food: Take immediately after meals.',
    'contraindication': 'Contraindicated in: Active peptic ulceration; Severe renal impairment; Severe heart failure; Asthma patients sensitive to NSAIDs; High blood pressure; History of Gastrointestinal bleeding; Last trimester of pregnancy; Severe liver disease.',
    'ageRestriction': '12',
    'interactions': [
      'aspirin',
      'warfarin', 
      'heparin',
      'pradaxa',
      'xarelto',
      'prednisone',
      'dexamethasone', 
      'methylprednisolone',
      'furosemide',
      'hydrochlorothiazide',
      'spironolactone',
      'ibuprofen',
      'diclofenac',
      'meloxicam',
      'celecoxib',
      'salbutamol',
      'ipratropium',
      'fluticasone',
      'montelukast'
    ],
    'activeIngredient': 'naproxen sodium'
  },

  {
    'name': 'Kremil-S',
    'genericName': 'Aluminum Hydroxide + Magnesium Hydroxide + Simethicone',
    'needsSpecificTiming': false,
    'categories': ['Antacid', 'Anti-flatulent'],
    'image': 'assets/images/medicines/kremil_s.png',
    'description': 'For the relief of heartburn, acid indigestion, and gastric discomfort.',
    'dosage': '178 mg Aluminum Hydroxide + 233 mg Magnesium Hydroxide + 30 mg Simethicone',
    'directions of use': '1-2 tablets to be chewed 4 times daily between meals and at bedtime.',
    'administration': 'Chew tablets thoroughly before swallowing.',
    'contraindication': 'Allergy to any ingredient in the product. If the patient has: Kidney disease, Intestinal obstruction, Appendicitis, Fecal impaction, Gastric outlet obstruction, Constipation, Phosphate depletion and low serum phosphate, Osteomalacia (softening of bones).',
    'ageRestriction': '12',
    'interactions': [
      'doxycycline',
      'minocycline',
      'tetracycline',
      'ferrous sulfate',
      'ferrous fumarate',
      'ciprofloxacin',
      'levofloxacin',
      'moxifloxacin',
      'ofloxacin'
    ],
    'activeIngredient': 'aluminum hydroxide, magnesium hydroxide, simethicone'
  },

  {
    'name': 'Kremil-S Advance',
    'genericName': 'Aluminum Hydroxide + Magnesium Hydroxide + Simethicone + Calcium Carbonate',
    'categories': ['Antacid', 'Anti-flatulent'],
    'image': 'assets/images/medicines/kremil_s_advance.png',
    'description': 'For the symptomatic relief of hyperacidity, heartburn, acid indigestion, sour stomach, and gas pain.',
    'dosage': '200 mg + 200 mg + 25 mg + 300 mg',
    'directions of use': 'Chew 1 tablets between meals and at bedtime, or as needed. Do not use more than 2 chewable tablets in 24 hours.',
    'administration': 'Should be taken on an empty stomach: Take 1 hr before or 2 hrs after meals. Chew tab completely before swallowing.',
    'contraindication': 'Severe kidney disease, hypercalcemia, hypophosphatemia.',
    'ageRestriction': '12',
    'interactions': [
      'doxycycline',
      'minocycline',
      'tetracycline',
      'ferrous sulfate',
      'ferrous fumarate',
      'ciprofloxacin',
      'levofloxacin',
      'moxifloxacin',
      'ofloxacin',
      'digoxin'
    ],
    'activeIngredient': 'aluminum hydroxide, magnesium hydroxide, simethicone, calcium carbonate'
  },

  {
    'name': 'Medicol Advance 200',
    'genericName': 'Ibuprofen',
    'categories': ['Pain Reliever', 'Fever', 'Headache'],
    'image': 'assets/images/medicines/medicol_advance.png',
    'description': 'For the relief of headache. For the relief of toothache, muscular aches, minor arthritis pain, backache, minor aches and pains associated with the common cold, and pain of menstrual cramps(dysmenorrhea). For fever reduction.',
    'dosage': '200 mg Ibuprofen',
    'directions of use': '1 capsule every 4-6 hours as needed. Maximum of 6 tablets in 24 hours.',
    'administration': 'Take with food.',
    'contraindication': 'Do not use if: History of allergic reactions to NSAIDs; Active peptic ulcer; Severe heart failure; Asthma triggered by NSAIDs; High blood pressure; Liver or kidney disease; Third trimester of pregnancy.',
    'ageRestriction': '12',
    'interactions': [
      'aspirin',
      'ibuprofen',
      'warfarin',
      'alcohol',
      'heparin',
      'lisinopril',
      'enalapril',
      'ramipril',
      'captopril',
      'furosemide',
      'hydrochlorothiazide',
      'spironolactone'
    ],
    'activeIngredient': 'ibuprofen'
  },

  {
    'name': 'Myracof',
    'genericName': 'Ambroxol Hydrochloride',
    'categories': ['Cough'],
    'image': 'assets/images/medicines/myracof.png',
    'description': 'For the relief of cough with mucus and respiratory tract congestion.',
    'dosage': '30 mg Ambroxol Hydrochloride',
    'directions of use': '1 tablet 3 times daily.',
    'administration': 'Take after meals.',
    'contraindication': 'Hypersensitivity to ambroxol or bromhexine.',
    'ageRestriction': '12',
    'interactions': [
      'dextromethorphan',
      'codeine',
      'butamirate citrate',
      'sinecod',
      'robitussin'
    ],
    'activeIngredient': 'ambroxol hydrochloride'
  },

  {
    'name': 'Neozep Z+ Forte',
    'genericName': 'Phenylephrine + Chlorphenamine + Paracetamol + Zinc',
    'categories': ['Cold', 'Flu', 'Fever'],
    'image': 'assets/images/medicines/neozep_z_plus_forte.png',
    'description': 'Relief of clogged & runny nose, postnasal drip, itchy & watery eyes, sneezing, headache & & body ache, & fever associated w/ common cold, allergic rhinitis, sinusitis, flu & other minor resp tract infections. Decongest sinus openings & passages & protect resp cells against common cold & flu. Treatment & prevention of Zn mineral deficiency.',
    'dosage': '10 mg Phenylephrine + 2 mg Chlorphenamine + 325 mg Paracetamol + 10 mg Zinc',
    'directions of use': '1 tablet every 6 hours as needed.',
    'administration': 'May be taken with or without food.',
    'contraindication': 'Hypersensitivity to components, severe hypertension, MAO inhibitor therapy.',
    'ageRestriction': '12',
    'interactions': [
      'selegiline',
      'phenelzine',
      'tranylcypromine',
      'moclobemide',
      'alprazolam',
      'diazepam',
      'lorazepam',
      'zolpidem',
      'alcohol',
      'ethanol',
      'lisinopril',
      'enalapril',
      'metoprolol',
      'paracetamol',
      'propranolol',
      'ferrous sulfate',
      'ferrous fumarate'
    ],
    'activeIngredient': 'phenylephrine, chlorphenamine, paracetamol, zinc'
  },

  {
    'name': 'No Drowse Decolgen',
    'genericName': 'Phenylpropanolamine Hyrdrochloride +  Paracetamol',
    'categories': ['Cold', 'Flu'],
    'image': 'assets/images/medicines/no_drowse_decolgen.png',
    'description': 'This medicine is used for the relief of clogged nose, postnasal drip, headache, body aches, and fever associated with the common cold, sinusitis, flu, and other minor respiratory tract infections. It also helps decongest sinus openings and passages.',
    'dosage': '25 mg Phenylpropanolamine Hyrdrochloride + 500 mg Paracetamol',
    'directions of use': '1 tablet every 6 hours as needed.',
    'administration': 'May be taken with or without food.',
    'contraindication': 'If the patient is allergic to any ingredient in the product. If the patient has high blood pressure or severe heart disease unless recommended by a doctor. If the patient has anemia, kidney or liver disease unless recommended by a doctor. If the patient is pregnant or breastfeeding.',
    'ageRestriction': '12',
    'interactions': [
      'selegiline',
      'phenelzine',
      'tranylcypromine',
      'moclobemide',
      'propranolol',
      'metoprolol',
      'atenolol',
      'lisinopril',
      'enalapril',
      'ramipril',
      'paracetamol',
      'alprazolam',
      'diazepam',
      'lorazepam',
      'zolpidem'
    ],
    'activeIngredient': 'phenylpropanolamine, chlorphenamine, paracetamol'
  },

  {
    'name': 'Sinecod Forte',
    'genericName': 'Butamirate Citrate',
    'categories': ['Cough'],
    'image': 'assets/images/medicines/sinecod_forte.png',
    'description': 'For the symptomatic relief of all forms of dry, irritative and allergic cough.',
    'dosage': '50 mg Butamirate Citrate',
    'directions of use': '1 tablet 3 times daily at least 8 hrs between does. Maximum of 3 tablets in 24 hours.',
    'administration': 'Take after meals.',
    'contraindication': 'Hypersensitivity to butamirate or any component.',
    'ageRestriction': '12',
    'interactions': [
      'alprazolam',
      'diazepam',
      'lorazepam',
      'zolpidem',
      'alcohol',
      'ethanol',
      'dextromethorphan',
      'codeine',
      'ambroxol',
      'carbocisteine'
    ],
    'activeIngredient': 'butamirate citrate'
  },

  {
    'name': 'Solmux Advance',
    'genericName': 'Carbocisteine + Zinc',
    'categories': ['Cough'],
    'image': 'assets/images/medicines/solmux_advance.png',
    'description': 'For the treatment of respiratory tract disorders characterized by excessive mucus secretion.',
    'dosage': '500 mg Carbocisteine + 5 mg Zinc',
    'directions of use': '1 capsule in every 8 hrs. 3 times daily. ',
    'administration': 'Take with meals.',
    'contraindication': 'If the patient is allergic to any ingredient in the product. This medicine should be given with care in patients with a history of stomach or intestinal ulcer and gastrointestinal bleeding. Taking multiple antitussive agents with carbocisteine is not recommended. This product provides close to the maximum daily intake of zinc when taken at the recommended dose of three times a day. To avoid excessive intake, refrain from using other supplements or medicines containing zinc. If you are not sure whether a medicine contains zinc, ask a doctor.',
    'ageRestriction': '12',
    'interactions': [
      'dextromethorphan',
      'codeine',
      'butamirate citrate',
      'sinecod'
    ],
    'activeIngredient': 'carbocisteine'
  },

  {
    'name': 'Tempra Forte',
    'genericName': 'Paracetamol',
    'categories': ['Fever', 'Pain Reliever', 'Flu'],
    'image': 'assets/images/medicines/tempra_forte.png',
    'description': 'Useful for reducing fever and for the temporary relief of minor aches, pains and discomfort associated with the common colds or flu, inoculations or vaccinations. It is also valuable in reducing pain following tonsillectomy and adenoidectomy.',
    'dosage': '500 mg Paracetamol',
    'directions of use': '1-2 tablets every 4-6 hours as needed. Maximum of 8 tablets in 24 hours.',
    'administration': 'May be taken with or without food.',
    'contraindication': 'Severe liver impairment, hypersensitivity to paracetamol.',
    'ageRestriction': '12',
    'interactions': [
      'alcohol',
      'ethanol',
      'warfarin',
      'phenobarbital',
      'paracetamol',
      'phenytoin',
      'carbamazepine',
      'rifampicin'
    ],
    'activeIngredient': 'paracetamol'
  },

  {
    'name': 'Tuseran Forte',
    'genericName': 'Dextromethorphan Hydrobromide + Phenylpropanolamine + Paracetamol',
    'categories': ['Cough', 'Cold', 'Flu', 'Fever' , 'Pain Reliever'],
    'image': 'assets/images/medicines/tuseran_forte.png',
    'description': 'This medicine is used for the relief of cough, clogged nose, postnasal drip, headache, body aches, and fever associated with the common cold, allergic rhinitis, sinusitis, flu, and other minor respiratory tract infections. It also helps decongest sinus openings and passages. ',
    'dosage': '15 mg Dextromethorphan Hydrobromide + 25 mg Phenylpropanolamine + 325 mg Paracetamol',
    'directions of use': '1 capsule every 6 hours.',
    'administration': 'May be taken with or without food.',
    'contraindication': 'If the patient is allergic to any ingredient of the product. If the patient has high blood pressure or severe heart disease unless recommended by a doctor. If the patient has anemia, kidney or liver disease unless recommended by a doctor. If the patient is pregnant or breastfeeding. ',
    'ageRestriction': '12',
    'interactions': [
      'selegiline',
      'phenelzine',
      'tranylcypromine',
      'moclobemide',
      'lisinopril',
      'enalapril',
      'ramipril',
      'metoprolol',
      'propranolol',
      'alprazolam',
      'diazepam',
      'paracetamol',
      'lorazepam',
      'zolpidem'
    ],
    'activeIngredient': 'dextromethorphan hydrobromide, phenylpropanolamine, paracetamol'
  }
];